version: '3.8'

services:
  movies:
    image: preetham312/paymovies:latest
    ports:
      - "81:80"
    deploy:
      replicas: 3

  train:
    image: preetham312/paytrain:latest
    ports:
      - "82:80"
    deploy:
      replicas: 3

  dth:
    image: preetham312/paydth:latest
    ports:
      - "83:80"
    deploy:
      replicas: 3

  recharge:
    image: preetham312/patrecharge:latest
    ports:
      - "84:80"
    deploy:
      replicas: 3
